//! UI module for notification popup windows
//!
//! Handles X11 window creation, Cairo rendering, and mouse interaction
//! for notification popups.

mod layout;
mod popup;
mod popup_manager;

pub use layout::{LayoutManager, NotificationPosition, StackDirection};
pub use popup::NotificationPopup;
pub use popup_manager::PopupManager;

use crate::notification::{CloseReason, Notification};

/// Commands that can be sent to the UI system
#[derive(Debug, Clone)]
pub enum PopupCommand {
    /// Show a notification popup
    Show(Notification),
    /// Update an existing notification (replacement)
    Update { id: u32, notification: Notification },
    /// Close a notification popup
    Close { id: u32, reason: CloseReason },
    /// Close all notification popups
    CloseAll,
}

/// Events generated by the UI system
#[derive(Debug, Clone)]
pub enum PopupEvent {
    /// User clicked to dismiss a notification
    Dismissed(u32),
    /// User clicked an action button
    ActionInvoked { id: u32, action_key: String },
    /// Notification popup was closed (animation finished, etc.)
    Closed { id: u32, reason: CloseReason },
}
